### ISSUE TITLE
sporadic error while running multiple sexy calls "a.removeEventListener is not a function"

### ISSUE THREAD

**Issue by Marak** [furf/Sexy#2]
Every once and while my ajax requests will not end or close then after a while I'll see the following error message.

I'm fairly certain that the server is responding correctly....

any ideas what could be causing this? 

http://skitch.com/timsmart/n4r1k/hook.io-the-free-web-hook-platform-about

**Comment by furf** [comment]
Funny, this just started happening to me tonight for the first time. It looks like it's related to the detaching of events bound using .one(). I quickly replaced them in my test code with .bind() and the problem seems to have disappeared. 

I'll take a deeper look at it tomorrow. In the meanwhile, I don't think there's any harm in going into your checkout and replacing "one" with "bind". To be honest, it would probably speed up the code a tad bit as well.

Though this solution seems to be working, I'd still like to explore the real issue before resolving. It seemed to occur on first refresh after a hard refresh. Perhaps an issue w/ caching?

Thanks for the continued support!

furf

**Comment by Marak** [comment]
Let me know if there is anything I could do to help you test. I'll wait a few days for an update and if you haven't had the chance to push by then I'll try your suggestion.

Thanks again Furf!

**Comment by Marak** [comment]
Replacing one with bind seems to work now.
